#!/usr/bin/env python3
"""
RAG System Demo — Westfield Industrial Plant Utility Documents

Demonstrates the full pipeline:
1. Load sample sensor/utility documents
2. Chunk and index them
3. Run several example queries (retrieval only if no API key is set)
4. Show index statistics

Usage:
    python main.py

Environment:
    ANTHROPIC_API_KEY  — Optional. Set for AI-generated answers.
                         Without it the system runs in retrieval-only mode.
"""

from __future__ import annotations

import logging
import os
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Minimal logging setup — show INFO from our own modules only
# ---------------------------------------------------------------------------

logging.basicConfig(
    format="%(levelname)s  %(name)s | %(message)s",
    level=logging.WARNING,
)
logging.getLogger("rag").setLevel(logging.INFO)

# ---------------------------------------------------------------------------
# Verify sample_docs exist
# ---------------------------------------------------------------------------

SAMPLE_DOCS_DIR = Path(__file__).parent / "sample_docs"
INDEX_PATH = Path(__file__).parent / ".rag_index" / "store.pkl"


def _check_sample_docs() -> None:
    if not SAMPLE_DOCS_DIR.exists():
        print(f"ERROR: sample_docs/ directory not found at {SAMPLE_DOCS_DIR}")
        sys.exit(1)
    files = list(SAMPLE_DOCS_DIR.iterdir())
    if not files:
        print(f"ERROR: sample_docs/ is empty — expected CSV, TXT, JSON, LOG files.")
        sys.exit(1)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _divider(title: str = "") -> None:
    width = 72
    if title:
        pad = (width - len(title) - 2) // 2
        print("=" * pad + f" {title} " + "=" * pad)
    else:
        print("=" * width)


def _ask(pipeline: "RAGPipeline", question: str, top_k: int = 5) -> None:
    """Helper: run a query and print the result."""
    print(f"\nQ: {question}")
    print("-" * 60)
    answer = pipeline.query(question, top_k=top_k)
    if answer.error:
        print(f"ERROR: {answer.error}")
    else:
        print(answer.answer)
    print()
    print(answer.format_citations())
    if answer.generation_used:
        print(f"\n[Generated by {answer.model}]")
    else:
        print("\n[Retrieval-only mode — set ANTHROPIC_API_KEY for AI answers]")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main() -> None:
    _divider("RAG Demo — Utility / Sensor Documents")

    _check_sample_docs()

    # Import here so any import errors are shown clearly
    try:
        from rag import RAGPipeline
        from rag.embeddings import TFIDFEmbedder
    except ImportError as exc:
        print(f"Import error: {exc}")
        print("Run:  pip install -r requirements.txt")
        sys.exit(1)

    # ------------------------------------------------------------------
    # 1. Build pipeline
    # ------------------------------------------------------------------
    _divider("Step 1: Initialise Pipeline")

    api_key = os.environ.get("ANTHROPIC_API_KEY", "")
    if api_key:
        print("ANTHROPIC_API_KEY found — generation mode enabled.")
    else:
        print("ANTHROPIC_API_KEY not set — running in retrieval-only mode.")
        print("(Set the environment variable to enable AI-generated answers.)")

    embedder = TFIDFEmbedder(max_features=8000, ngram_range=(1, 2))
    pipeline = RAGPipeline(
        embedder=embedder,
        chunk_size=512,
        chunk_overlap=64,
        rows_per_chunk=15,
        top_k=5,
        dense_weight=0.55,
        bm25_weight=0.45,
        model="claude-sonnet-4-6",
        max_tokens=1024,
    )

    # ------------------------------------------------------------------
    # 2. Index sample documents
    # ------------------------------------------------------------------
    _divider("Step 2: Index Sample Documents")

    print(f"Loading documents from: {SAMPLE_DOCS_DIR}")
    n_chunks = pipeline.index_directory(SAMPLE_DOCS_DIR)
    print(f"Indexed {n_chunks} chunks.\n")

    # Show stats
    stats = pipeline.stats()
    idx = stats["index_stats"]
    print(f"Total chunks: {idx['num_chunks']}")
    print(f"Embedding dim: {idx['embedding_dim']}")
    print(f"Embedder: {idx['embedder']}")
    print("\nDocument types:")
    for t, c in sorted(idx["types"].items()):
        print(f"  {t:<12} {c} chunk(s)")
    print("\nFiles indexed:")
    for src, c in sorted(idx["sources"].items()):
        print(f"  {Path(src).name:<45} {c} chunk(s)")

    # Save index for CLI use
    INDEX_PATH.parent.mkdir(parents=True, exist_ok=True)
    pipeline.save_index(INDEX_PATH)
    print(f"\nIndex saved to: {INDEX_PATH}")
    print("(Use `python -m rag.cli query \"...\" --index-path .rag_index/store.pkl` to query)")

    # ------------------------------------------------------------------
    # 3. Example queries
    # ------------------------------------------------------------------
    _divider("Step 3: Example Queries")

    queries = [
        "What temperature anomalies or critical events were recorded on 2024-01-15?",
        "What caused the pump failure and what was the repair procedure?",
        "Which sensors recorded critical alert levels and what were the peak values?",
        "What is the maximum allowable pressure for Pipeline Section 3 and what happened during the event?",
        "What maintenance actions are overdue or scheduled for Q1 2024?",
        "What are the design specifications of the centrifugal coolant pump P-204?",
    ]

    for q in queries:
        _divider()
        _ask(pipeline, q, top_k=5)

    # ------------------------------------------------------------------
    # 4. Dense vs BM25 comparison (optional demo)
    # ------------------------------------------------------------------
    _divider("Step 4: Search Mode Comparison")

    demo_query = "vibration pump bearing failure"
    print(f"Query: {demo_query!r}\n")

    print("-- Dense (cosine similarity) top 3 --")
    for r in pipeline._vector_store.search_dense(demo_query, top_k=3):
        src = Path(r.source).name
        preview = r.content[:120].replace("\n", " ")
        print(f"  [{r.rank}] {src} score={r.score:.4f}  {preview}...")

    print("\n-- BM25 (keyword) top 3 --")
    for r in pipeline._vector_store.search_bm25(demo_query, top_k=3):
        src = Path(r.source).name
        preview = r.content[:120].replace("\n", " ")
        print(f"  [{r.rank}] {src} score={r.score:.4f}  {preview}...")

    print("\n-- Hybrid top 3 --")
    for r in pipeline._vector_store.search(demo_query, top_k=3):
        src = Path(r.source).name
        preview = r.content[:120].replace("\n", " ")
        print(f"  [{r.rank}] {src} score={r.score:.4f}  {preview}...")

    _divider()
    print("\nDemo complete.")
    print("\nTo use the CLI:")
    print("  python -m rag.cli query \"your question\" --index-path .rag_index/store.pkl")
    print("  python -m rag.cli interactive --index-path .rag_index/store.pkl")
    print("  python -m rag.cli stats --index-path .rag_index/store.pkl")
    print()


if __name__ == "__main__":
    main()
