"""
RAG Pipeline — main orchestrator for the Retrieval-Augmented Generation system.

Responsibilities:
- Index documents from a directory or explicit file list
- Retrieve relevant chunks for a query (hybrid search)
- Generate answers with Anthropic Claude using retrieved context
- Format source citations
- Graceful degradation when ANTHROPIC_API_KEY is not set
"""

from __future__ import annotations

import logging
import os
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from .chunker import Chunk, TextChunker
from .embeddings import EmbeddingModel, TFIDFEmbedder, get_default_embedder
from .loaders import Document, load_directory, load_document
from .vector_store import SearchResult, VectorStore

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Answer dataclass
# ---------------------------------------------------------------------------


@dataclass
class RAGAnswer:
    """The result of a RAG query."""

    query: str
    answer: str
    sources: list[dict[str, Any]] = field(default_factory=list)
    retrieved_chunks: list[SearchResult] = field(default_factory=list)
    generation_used: bool = False
    model: str = ""
    error: str = ""

    def format_citations(self) -> str:
        """Return a human-readable citation block."""
        if not self.sources:
            return "No sources found."
        lines = ["Sources:"]
        seen: set[str] = set()
        rank = 1
        for src in self.sources:
            key = f"{src.get('source', '')}:{src.get('chunk_index', '')}"
            if key in seen:
                continue
            seen.add(key)
            source_name = Path(src.get("source", "unknown")).name
            chunk_idx = src.get("chunk_index", "?")
            doc_type = src.get("type", "?")
            score = src.get("score", 0.0)
            lines.append(
                f"  [{rank}] {source_name} (chunk {chunk_idx}, type={doc_type}, score={score:.3f})"
            )
            rank += 1
        return "\n".join(lines)

    def __str__(self) -> str:
        header = f"Q: {self.query}\n"
        if self.error:
            return header + f"Error: {self.error}"
        body = f"A: {self.answer}\n\n{self.format_citations()}"
        if self.generation_used:
            body += f"\n\n[Generated by {self.model}]"
        else:
            body += "\n\n[Retrieval-only mode — no generation API key]"
        return header + body


# ---------------------------------------------------------------------------
# Pipeline
# ---------------------------------------------------------------------------

_SYSTEM_PROMPT = """You are an expert utility and sensor data analyst assistant.
You help engineers, technicians, and operations teams understand sensor logs,
maintenance reports, equipment specifications, and alert events.

When answering questions:
1. Base your answer ONLY on the provided context documents.
2. Quote specific values, timestamps, units, and identifiers when relevant.
3. If you detect anomalies, out-of-range readings, or critical alerts in the data,
   flag them clearly.
4. For sensor data, mention the time range, sensor IDs, and measurement units.
5. If the context does not contain enough information, say so clearly rather than
   guessing or hallucinating data.
6. Keep answers concise but precise — this is an operational context where accuracy
   matters more than verbosity.
7. When citing numbers from sensor readings, always include the unit of measure.
"""


class RAGPipeline:
    """
    End-to-end RAG pipeline for utility/sensor documents.

    Example usage::

        pipeline = RAGPipeline()
        pipeline.index_directory("sample_docs/")
        answer = pipeline.query("What is the maximum temperature recorded?")
        print(answer)
    """

    def __init__(
        self,
        embedder: EmbeddingModel | None = None,
        chunker: TextChunker | None = None,
        chunk_size: int = 512,
        chunk_overlap: int = 64,
        rows_per_chunk: int = 20,
        top_k: int = 5,
        dense_weight: float = 0.6,
        bm25_weight: float = 0.4,
        model: str = "claude-sonnet-4-6",
        max_tokens: int = 2048,
        index_path: str | None = None,
    ) -> None:
        """
        Initialise the RAG pipeline.

        Args:
            embedder: Embedding model. Defaults to best available.
            chunker: TextChunker instance. Defaults to sensible values.
            chunk_size: Characters per chunk (for text docs).
            chunk_overlap: Overlap between chunks.
            rows_per_chunk: Rows per chunk for CSV/log docs.
            top_k: Number of chunks to retrieve per query.
            dense_weight: Weight for dense search in hybrid mode.
            bm25_weight: Weight for BM25 in hybrid mode.
            model: Anthropic model identifier for generation.
            max_tokens: Max tokens for generated answer.
            index_path: If provided, auto-save/load index from this path.
        """
        self._embedder = embedder or get_default_embedder()
        self._chunker = chunker or TextChunker(
            chunk_size=chunk_size,
            chunk_overlap=chunk_overlap,
            rows_per_chunk=rows_per_chunk,
        )
        self._vector_store = VectorStore(self._embedder)
        self._top_k = top_k
        self._dense_weight = dense_weight
        self._bm25_weight = bm25_weight
        self._model = model
        self._max_tokens = max_tokens
        self._index_path = Path(index_path) if index_path else None
        self._indexed_files: list[str] = []

        # Try to load existing index
        if self._index_path and self._index_path.exists():
            self._load_index()

        # Check API key availability
        self._api_key = os.environ.get("ANTHROPIC_API_KEY", "")
        if not self._api_key:
            logger.warning(
                "ANTHROPIC_API_KEY not set. The pipeline will operate in "
                "retrieval-only mode (no answer generation)."
            )

    # ------------------------------------------------------------------
    # Indexing
    # ------------------------------------------------------------------

    def index_directory(
        self,
        directory: str | Path,
        extensions: list[str] | None = None,
        recursive: bool = True,
    ) -> int:
        """
        Load and index all documents in a directory.

        Args:
            directory: Path to the directory.
            extensions: File extensions to include (defaults to all supported).
            recursive: Whether to recurse into sub-directories.

        Returns:
            Number of chunks indexed.
        """
        logger.info("Loading documents from directory: %s", directory)
        documents = load_directory(directory, extensions=extensions, recursive=recursive)
        return self._index_documents(documents)

    def index_files(self, files: list[str | Path]) -> int:
        """
        Load and index an explicit list of files.

        Args:
            files: List of file paths to index.

        Returns:
            Number of chunks indexed.
        """
        documents: list[Document] = []
        for fp in files:
            try:
                docs = load_document(fp)
                documents.extend(docs)
            except Exception as exc:  # noqa: BLE001
                logger.warning("Failed to load %s: %s", fp, exc)
        return self._index_documents(documents)

    def _index_documents(self, documents: list[Document]) -> int:
        """Internal: chunk + embed + store documents."""
        if not documents:
            logger.warning("No documents to index.")
            return 0

        logger.info("Chunking %d documents...", len(documents))
        chunks = self._chunker.chunk_documents(documents)
        logger.info("Produced %d chunks.", len(chunks))

        if not chunks:
            logger.warning("Chunking produced no chunks.")
            return 0

        self._vector_store.add_chunks(chunks)
        self._indexed_files.extend(
            {doc.source for doc in documents} - set(self._indexed_files)
        )

        if self._index_path:
            self._save_index()

        return len(chunks)

    # ------------------------------------------------------------------
    # Query / retrieval
    # ------------------------------------------------------------------

    def retrieve(self, query: str, top_k: int | None = None) -> list[SearchResult]:
        """
        Retrieve the most relevant chunks for a query.

        Args:
            query: Natural language query.
            top_k: Override default top_k.

        Returns:
            List of SearchResult objects.
        """
        if not self._vector_store.is_indexed:
            logger.error("Index is empty. Call index_directory() or index_files() first.")
            return []

        k = top_k or self._top_k
        return self._vector_store.search(
            query,
            top_k=k,
            dense_weight=self._dense_weight,
            bm25_weight=self._bm25_weight,
        )

    def query(
        self,
        question: str,
        top_k: int | None = None,
        include_context: bool = False,
    ) -> RAGAnswer:
        """
        Ask a question and get a generated (or retrieval-only) answer.

        Args:
            question: Natural language question.
            top_k: Override default number of retrieved chunks.
            include_context: If True, include raw chunk content in answer object.

        Returns:
            RAGAnswer with answer, sources, and optional context.
        """
        if not self._vector_store.is_indexed:
            return RAGAnswer(
                query=question,
                answer="",
                error="Index is empty. Please index documents first.",
            )

        # 1. Retrieve relevant chunks
        results = self.retrieve(question, top_k=top_k)
        if not results:
            return RAGAnswer(
                query=question,
                answer="No relevant documents found for your query.",
                retrieved_chunks=results,
            )

        # 2. Build context string
        context = self._format_context(results)

        # 3. Build sources list
        sources = [
            {
                **r.metadata,
                "score": r.score,
                "search_type": r.search_type,
            }
            for r in results
        ]

        # 4. Generate answer (or fall back to retrieval summary)
        if self._api_key:
            answer, error = self._generate(question, context)
            generation_used = error == ""
        else:
            answer = self._retrieval_only_answer(question, results)
            error = ""
            generation_used = False

        ans = RAGAnswer(
            query=question,
            answer=answer,
            sources=sources,
            retrieved_chunks=results if include_context else [],
            generation_used=generation_used,
            model=self._model if generation_used else "",
            error=error,
        )
        return ans

    # ------------------------------------------------------------------
    # Context formatting
    # ------------------------------------------------------------------

    def _format_context(self, results: list[SearchResult]) -> str:
        """Format retrieved chunks into a context string for the LLM."""
        parts: list[str] = []
        for i, result in enumerate(results, start=1):
            source_name = Path(result.source).name
            chunk_idx = result.metadata.get("chunk_index", "?")
            doc_type = result.metadata.get("type", "?")
            parts.append(
                f"--- Document {i} ---\n"
                f"Source: {source_name} | Type: {doc_type} | Chunk: {chunk_idx} | Score: {result.score:.3f}\n\n"
                f"{result.content}\n"
            )
        return "\n".join(parts)

    @staticmethod
    def _retrieval_only_answer(question: str, results: list[SearchResult]) -> str:
        """
        Return a retrieval-only answer summarising the top chunks.

        Used when no API key is set.
        """
        lines = [
            f"[Retrieval-only mode] Top {len(results)} relevant passage(s) for: {question!r}",
            "",
        ]
        for i, result in enumerate(results, start=1):
            source_name = Path(result.source).name
            preview = result.content[:300].replace("\n", " ")
            lines.append(f"[{i}] From {source_name} (score={result.score:.3f}):")
            lines.append(f"    {preview}...")
            lines.append("")
        return "\n".join(lines)

    # ------------------------------------------------------------------
    # Generation
    # ------------------------------------------------------------------

    def _generate(self, question: str, context: str) -> tuple[str, str]:
        """
        Call the Anthropic Claude API to generate an answer.

        Returns:
            Tuple of (answer_text, error_string).
            error_string is empty on success.
        """
        try:
            import anthropic
        except ImportError:
            return (
                "",
                "anthropic package not installed. Run: pip install anthropic",
            )

        prompt = (
            f"Context documents:\n\n{context}\n\n"
            f"Question: {question}\n\n"
            "Please answer the question based solely on the context documents above. "
            "Include specific values, timestamps, and units where relevant. "
            "If the context does not contain sufficient information, say so."
        )

        try:
            client = anthropic.Anthropic()  # reads ANTHROPIC_API_KEY from env
            response = client.messages.create(
                model=self._model,
                max_tokens=self._max_tokens,
                system=_SYSTEM_PROMPT,
                messages=[{"role": "user", "content": prompt}],
            )
            answer = response.content[0].text
            logger.debug(
                "Generation complete. Input tokens: %d, Output tokens: %d",
                response.usage.input_tokens,
                response.usage.output_tokens,
            )
            return answer, ""
        except Exception as exc:  # noqa: BLE001
            error_msg = f"Generation failed: {exc}"
            logger.error(error_msg)
            return "", error_msg

    # ------------------------------------------------------------------
    # Persistence
    # ------------------------------------------------------------------

    def _save_index(self) -> None:
        """Save the vector store to disk."""
        if self._index_path:
            self._vector_store.save(self._index_path)

    def _load_index(self) -> None:
        """Load the vector store from disk."""
        if self._index_path and self._index_path.exists():
            try:
                self._vector_store = VectorStore.from_disk(
                    self._index_path, self._embedder
                )
                logger.info("Loaded existing index from %s", self._index_path)
            except Exception as exc:  # noqa: BLE001
                logger.warning("Could not load existing index: %s", exc)

    def save_index(self, path: str | Path) -> None:
        """Manually save the index to a specified path."""
        self._vector_store.save(path)
        logger.info("Index saved to %s", path)

    @classmethod
    def load_index(
        cls,
        path: str | Path,
        embedder: EmbeddingModel | None = None,
        **kwargs: Any,
    ) -> "RAGPipeline":
        """
        Create a pipeline from a saved index.

        Args:
            path: Path to the saved vector store.
            embedder: Optional embedder override.
            **kwargs: Additional pipeline constructor arguments.

        Returns:
            A RAGPipeline with the loaded index.
        """
        emb = embedder or TFIDFEmbedder()
        pipeline = cls(embedder=emb, **kwargs)
        pipeline._vector_store = VectorStore.from_disk(path, emb)
        return pipeline

    # ------------------------------------------------------------------
    # Introspection
    # ------------------------------------------------------------------

    def stats(self) -> dict[str, Any]:
        """Return statistics about the pipeline and index."""
        store_stats = self._vector_store.stats()
        return {
            "index_stats": store_stats,
            "indexed_files": self._indexed_files,
            "num_indexed_files": len(self._indexed_files),
            "top_k": self._top_k,
            "dense_weight": self._dense_weight,
            "bm25_weight": self._bm25_weight,
            "model": self._model,
            "api_available": bool(self._api_key),
            "embedder": repr(self._embedder),
        }

    def __repr__(self) -> str:
        return (
            f"RAGPipeline(chunks={self._vector_store.num_chunks}, "
            f"model={self._model!r}, api={bool(self._api_key)})"
        )
